#!/usr/bin/python3
#	gerberpeek - Render RS-274X Gerber files to image
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of gerberpeek.
#
#	gerberpeek is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	gerberpeek is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import gerber

filename = sys.argv[1]
#cctx = gerber.CairoContext.create_inches(gerber.Vector2d(7, 7), dpi = 300)
#callback = gerber.CairoCallback(cctx, src_color = (1, 0, 0))

callback = gerber.SizeDeterminationCallback()
gerber.Interpreter(filename, callback).run()
dimensions = callback.max_pt - callback.min_pt

#cctx.write_to_png("output.png")
