#!/usr/bin/python3
#	gerberpeek - Render RS-274X Gerber files to image
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of gerberpeek.
#
#	gerberpeek is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	gerberpeek is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import gerber
import math

cctx = gerber.CairoContext.create_inches(gerber.Vector2d(4, 4), dpi = 300)
cctx.fill(color = (0, 1, 0))

eraser = gerber.ApertureGenerator.generate_x(color = "red", size = 50, width = 10)
cctx.set_mode_erase()
eraser.blit_on_pixel(cctx, point = gerber.Vector2d(cctx.width / 2, cctx.height / 2))

cctx.write_to_png("eraser.png")
