#!/usr/bin/python3
#	gerberpeek - Render RS-274X Gerber files to image
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of gerberpeek.
#
#	gerberpeek is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	gerberpeek is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import gerber
import math

# Red base
red = gerber.CairoContext(dimensions = gerber.Vector2d(100, 50), offset = gerber.Vector2d(100, 100), dpi = 72)
red.fill(color = (1, 0, 0))
red.dump("red")

# Green hat
green = gerber.CairoContext(dimensions = gerber.Vector2d(50, 50), offset = gerber.Vector2d(125, 150), dpi = 72)
green.fill(color = (0, 1, 0))
green.dump("green")

# Blue dot
blue = gerber.CairoContext(dimensions = gerber.Vector2d(25, 25), offset = gerber.Vector2d(200, 200), dpi = 72)
blue.fill(color = (0, 0, 1))
blue.dump("blue")

# Compose them
src = [ red, green, blue ]
comp = gerber.CairoContext.create_composition_canvas(src)
comp.dump("comp")
comp.compose_all(src)
comp.write_to_png("composition.png")
